### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by rashibudati** [rohanrao619/Aadhaar_Card_OCR_and_Verification#1]
I am passing a jpg file directly. The issue persists even though I pass a pdf file.

IndexError                                Traceback (most recent call last)
<ipython-input-35-b16b64fe3782> in <module>()
      9 #   masked_img,possible_UIDs = Extract_and_Mask_UIDs('pdf2img.jpg')
     10 # else:
---> 11 masked_img,possible_UIDs = Extract_and_Mask_UIDs(input_path)
     12 
     13 if masked_img!=None and input_path.split('.')[-1]=="pdf":

<ipython-input-34-5835904f4bf3> in Regex_Search(bounding_boxes)
      8   for character in range(len(bounding_boxes)):
      9     # print(bounding_boxes[character])
---> 10     Result = Result + bounding_boxes[character][0]
     11     # print(Result)
     12 

IndexError: string index out of range

**Comment by rohanrao619** [comment]
Hi Rashi,

Glad that you reached out! I am sorry for the late reply.
I have fixed the issue on Github now, you can take the new code from there.

To be more specific, Try replacing lines 8-9 in the Regex_Search function
cell with the code given below :

for character in range(len(bounding_boxes)):
  if len(bounding_boxes[character])!=0:
    Result += bounding_boxes[character][0]
  else:
    Result += '?'

Let me know if it worked. If you face any other issues, feel free to mail
me.

Regards,
Rohan
